apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-movement
  labels:
    app: service-movement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-movement
  template:
    metadata:
      labels:
        app: service-movement
    spec:
      containers:
      - name: app-movement
        image: jeanflores2c93/aforo255-nodejs-movement:latest
        ports:
        - containerPort: 5005
        env:
        - name: NACOS_SERVERADDR
          value: "161.35.233.217:8848"
        - name: NACOS_NAMESPACE
          value: "aforo255"
        - name: NACOS_IDENTITYKEY
          value: "nacos"
        - name: NACOS_IDENTITYVALUE
          value: "nacos"
        - name: NACOS_ENV
          value: "PROD"
