kind: Service
apiVersion: v1
metadata:
  name: app-service-movement
spec:
  type: ClusterIP
  selector:
    app: service-movement
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5005
    name: http